# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d601bb3e553f271a6003458b8b5ecb847ba9960f6e706f6693328d6fbd46d01d98472d3faa63d2b724675e9d8e870df51cdba0685af3051ad09f15fe135d3b

test:
  secret_key_base: 1ce4857ea358575d08b426bb9b4b8990b2486b32c0977ce94949045f535f4abbe83f2f67318a4ebc8a04fd9a06acbdad9e5c864772d9a66a55ecef824e0e8c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
